### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by crogers2287** [jjclark1982/factorio-control-panel#1]
Whenever I run /usr/local/bin/factorio-control-panel

I receive this error:

```
/usr/local/lib/node_modules/factorio-control-panel/server.js:37
admin.get('/', (req, res, next)=>{
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

```

The server never starts.

**Comment by crogers2287** [comment]
Feel free to close.

For some reason node wasn't being installed as the most current version. Once updated server launched fine.

**Comment by HeilTec** [comment]
http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions
